# local config example

server:
  port: 9000
  host: "localhost"

database:
  host: "db.local.dev"
  port: 5432
  user: "dev_user"
  password: "dev_password"
  name: "myapp_dev"
  sslMode: "disable"

smtp:
  host: "sandbox.smtp.mailtrap.io"
  port: 2525
  user: "my-mailtrap-username"
  password: "my-mailtrap-password"
  charset: "my-charset"
  jwtSecret: "my-jwt-secret"

redis:
  address: "localhost:6379"
  password: ""
  db: 0